version: '3.8'

services:
  mysql:
    image: mysql:8
    volumes:
      - mysql_vol:/var/lib/mysql
    env_file:
      - ./.env

  web:
    build: ../app
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "80:8000"
    env_file:
      - ./.env
    depends_on:
      - mysql

volumes:
  mysql_vol: